name: build-release
on:
  push:
    tags:
      - 'stable'
  workflow_dispatch:
jobs:
  build-neovim:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install -y ninja-build gettext cmake curl build-essential
      - name: Get repo
        uses: actions/checkout@v4
        # with:
        #   ref: stable
      - name: Build neovim
        run: make CMAKE_BUILD_TYPE=Release
      - name: Create deb package
        run: cd build && cpack -G DEB
      - name: Upload the deb package
        uses: actions/upload-artifact@v4
        with:
          name: neovim-linux-stable
          path: build/nvim-linux-*.deb
  # release-neovim:
  #   runs-on: ubuntu-latest
  #   needs: build-neovim
  #   steps:
  #     - name: Download neovim package artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: neovim-linux-stable
  #     - name: Create Release
  #       uses: ncipollo/release-action@v1
  #       with:
  #         tag:
  #         artifacts: neovim-linux-stable/*.deb
